apiVersion: v1
kind: Service
metadata:
  namespace: polar
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 9002
      protocol: TCP
